CREATE DATABASE MONETARIO

USE MONETARIO

CREATE TABLE PAIS
(
ID_PAIS INT NOT NULL IDENTITY(1,1) CONSTRAINT pk_id_pais PRIMARY KEY
,DESCRIPCION VARCHAR(50)
)

CREATE TABLE IDIOMA
(
ID_IDIOMA INT NOT NULL IDENTITY(1,1) CONSTRAINT pk_id_idioma PRIMARY KEY
,DESC_IDIOMA VARCHAR(50) NOT NULL
)

CREATE TABLE TIPO_RIESGO
(
ID_RIESGO INT NOT NULL IDENTITY(1,1) CONSTRAINT pk_id_riesgo PRIMARY KEY
,DESC_RIESGO VARCHAR(5) NOT NULL
)

CREATE TABLE GESTIONPRESTAMO
(
ID_GESTION INT NOT NULL IDENTITY(1,1) CONSTRAINT pk_id_gestion PRIMARY KEY
,ID_PAIS INT NOT NULL CONSTRAINT fk_id_pais FOREIGN KEY REFERENCES PAIS(ID_PAIS)
,CANT_HABIT INT NOT NULL
,ID_IDIOMA INT NOT NULL CONSTRAINT fk_id_idioma FOREIGN KEY REFERENCES IDIOMA(ID_IDIOMA)
,PIB DECIMAL(8,2) NOT NULL
,SUPERFICIE DECIMAL(8,2) NOT NULL
,RIESGO VARCHAR(5) NOT NULL
,PRESTAMO BIT NOT NULL
)

SELECT
P.DESCRIPCION AS PAIS
,GP.CANT_HABIT AS HABITANTES
,I.DESC_IDIOMA AS IDIOMA
,GP.PIB
,GP.SUPERFICIE
,RIESGO
,CASE
	WHEN GP.PRESTAMO = 0
		THEN 'NO'
		ELSE 'SI'
	END
	AS PRESTAMO
FROM GESTIONPRESTAMO GP
	JOIN PAIS P
	ON GP.ID_PAIS = P.ID_PAIS
		JOIN IDIOMA I
		ON I.ID_IDIOMA = GP.ID_IDIOMA
			

SELECT * FROM GESTIONPRESTAMO

INSERT INTO PAIS
(
DESCRIPCION
)
VALUES
('Costa Rica')
,('Korea')
,('USA')
,('Mexico')
,('Nicaragua')
,('Canada')
,('Espana')
,('Inglaterra')
,('Argentina')
,('Brasil')
,('Japon')
,('Mongolia')
,('Honduras')
,('Nigeria')
,('Australia')

SELECT * FROM PAIS

INSERT INTO IDIOMA
(
DESC_IDIOMA
)
VALUES
('Español')
,('Koreano')
,('Ingles')
,('Frances')
,('Mandarin')
,('Portugues')
,('Aleman')
,('Mongol')
,('Arabe')
,('Ruso')
,('Hausa')

SELECT * FROM IDIOMA

INSERT INTO TIPO_RIESGO
(
DESC_RIESGO
)
VALUES
('Alto')
,('Medio')
,('Bajo')

INSERT INTO GESTIONPRESTAMO
(
ID_PAIS
,CANT_HABIT
,ID_IDIOMA
,PIB
,SUPERFICIE
,RIESGO
,PRESTAMO
)
VALUES
(1,5300000,1,12690,51100,'Bajo',1)
,(2,15300000,2,18690,551100,'Alto',0)
,(3,35300000,3,92690,451100,'Medio',1)

TRUNCATE TABLE GESTIONPRESTAMO